# Generated by Django 4.1.3 on 2023-07-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titie',
            new_name='title',
        ),
    ]
